#
# Source Prezto.
#

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Setting up theme
#

autoload -U promptinit
promptinit
# prompt adam2 8bit
# alias adam2='prompt adam2 8bit'
# alias adam2-light='prompt adam2 8bit cyan black black black magenta'

#
# Loading color theme
#

eval `dircolors $HOME/.dircolors`

#
# Prevent annoying terminal freezes
#

stty stop undef

#
# Tmux
#

alias mux="tmuxinator"
# no automatic renaming
export DISABLE_AUTO_TITLE=true

#
# Euler
#

alias cwm="python $HOME/system/scripts/cwm/cwm"

#
# Vim
#

if type gvim > /dev/null; then
    alias vim="gvim -v"
fi

#
# Todo.txt
#

export TODOTXT_DEFAULT_ACTION=top
export TODO_DIR=$HOME/system/todo
alias tw="todo.sh -d $TODO_DIR/work/work.cfg"
alias tp="todo.sh -d $TODO_DIR/personal/personal.cfg"
alias t="rm -f $TODO_DIR/todo.txt; rm -f $TODO_DIR/done.txt; cat $TODO_DIR/personal/todo.txt $TODO_DIR/work/todo.txt > $TODO_DIR/todo.txt; cat $TODO_DIR/personal/done.txt $TODO_DIR/work/done.txt > $TODO_DIR/done.txt; todo.sh -d $TODO_DIR/all.cfg"

#
# Fasd
#
alias jv="fasd -f -e vim"
alias jo="fasd -f -e xdg-open"

#
# Advanced cp
#

alias cp='acp -g'

#
# Non-interactive rm
#

alias rmf='rm -f'

#
# Virtualenv
#

export WORKON_HOME=$HOME/.virtualenvs
alias v='workon'
alias v.deactivate='deactivate'
alias v.mk='mkvirtualenv'
alias v.rm='rmvirtualenv'
alias v.add2virtualenv='add2virtualenv'
alias v.cdsitepackages='cdsitepackages'
alias v.cd='cdvirtualenv'
alias v.lssitepackages='lssitepackages'
