#
# Source Prezto.
#

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Setting up theme
#

autoload -U promptinit
promptinit
# prompt adam2 8bit
# alias adam2='prompt adam2 8bit'
# alias adam2-light='prompt adam2 8bit cyan black black black magenta'

#
# Loading color theme
#

BASE16_SHELL="$HOME/.config/base16-shell/base16-railscasts.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

eval `dircolors $HOME/.dircolors`

#
# Prevent annoying terminal freezes
#

stty stop undef

#
# Tmux
#

alias mux="tmuxinator"
# no automatic renaming
export DISABLE_AUTO_TITLE=true

#
# Euler
#

alias cwm="python $HOME/system/scripts/cwm/cwm"

#
# Vim
#

if type gvim > /dev/null; then
    alias vim="gvim -v"
fi

#
# Fasd
#
alias jv="fasd -f -e vim"
alias jo="fasd -f -e xdg-open"

#
# Todo.txt
#
alias t="todo.sh"
alias tv="vim $HOME/braindump/tasks/todo.txt"

#
# Advanced cp
#

if type acp > /dev/null; then
    alias cp='acp -g'
fi

#
# Non-interactive rm
#

alias rmf='rm -f'

#
# Working on integration
#
function on() { noglob curl -X POST --data-urlencode "task=$*" https://api.workingon.co/hooks/incoming?token=0244f71531a5292a0e5744942cef622446a33da391b6f4eb91c1381a8e715aee >/dev/null 2>&1 echo "Task sent." }

#
# Virtualenv
#

export WORKON_HOME=$HOME/.virtualenvs
alias v='workon'
alias v.deactivate='deactivate'
alias v.mk='mkvirtualenv'
alias v.rm='rmvirtualenv'
alias v.add2virtualenv='add2virtualenv'
alias v.cdsitepackages='cdsitepackages'
alias v.cd='cdvirtualenv'
alias v.lssitepackages='lssitepackages'

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
